### ISSUE TITLE
alrt.io is down

### ISSUE THREAD

**Issue by nikolas** [juliangruber/alrt.io#17]
http://alrt.io/ !!

**Comment by juliangruber** [comment]
yup, i had to give up hosting for it. do you want to take it over?

**Comment by nikolas** [comment]
I figured.. I would take over, because I found this site really useful, but after looking at the codebase, I'm not sure if I have time to bring the code up-to-date. For example, it looks like component.js is [deprecated](https://github.com/componentjs/component).
